### ISSUE TITLE
Bug: We aren't escaping filter values properly when filters are added through UI

### ISSUE THREAD

**Issue by anikaks** [malloydata/malloy#934]
When I try to add `Levi's` through the filter UI in the composer, I can't save it:

<img width="564" alt="Screen Shot 2022-11-14 at 3 23 26 PM" src="https://user-images.githubusercontent.com/7178946/201788664-5be7b661-6d09-4adb-bdf7-6b3fc3d2f073.png">

I get these errors in the console

```
Error: Error(s) compiling model:
FILE: internal://internal.malloy
line 1: extraneous input 's' expecting {AGGREGATE, DECLARE, GROUP_BY, HAVING, INDEX, JOIN_CROSS, JOIN_ONE, JOIN_MANY, LIMIT, NEST, ORDER_BY, PROJECT, SAMPLE, TOP, WHERE, '}', ';'}
  | query: the_query is order_items -> { group_by: one is 1; where: inventory_items.product_brand = 'Levi's'}
  |                                                                                                       ^
line 1: mismatched input ''' expecting {AGGREGATE, DECLARE, GROUP_BY, HAVING, INDEX, JOIN_CROSS, JOIN_ONE, JOIN_MANY, LIMIT, NEST, ORDER_BY, PROJECT, SAMPLE, TOP, WHERE, AND, DAY, FOR, HOUR, MINUTE, MONTH, OR, '?', QUARTER, SECOND, TO, WEEK, YEAR, '&', '{', '}', '::', ':', ',', '.', '<', '>', '=', '!=', '<=', '>=', '+', '-', '*', '/', '|', ';', '!~', '~'}
  | query: the_query is order_items -> { group_by: one is 1; where: inventory_items.product_brand = 'Levi's'}
  |                                                                                                        ^
    at Gc.compile (app.js:1214:4987)
    at P3e (app.js:2275:743)
    at async U3e (app.js:2275:921)
    at async Hg (app.js:2275:1140)
    ```

**Comment by anikaks** [comment]
Assigning to you @christopherswenson since you'll be touching filter stuff shortly
